import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Navbar from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Techconnectors</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/techconnectors-logo.png" />
        {/* catamaran font  */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Catamaran&display=swap"
          rel="stylesheet"
        />
        {/* catamaran font  */}
        {/* fjalla font  */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap"
          rel="stylesheet"
        />
        {/* fjalla font  */}
      </Head>
      <Navbar />
      <main className="">
        <div className="dotted-bg flex flex-col items-center  justify-center gap-3 border pb-16 pt-20 ">
          <h1 className="font-fjalla text-5xl font-semibold tracking-tight">
            Conectando tecnología con tus necesidades.
          </h1>
          <h1 className="font-fjalla text-5xl font-semibold tracking-tight">
            Experimenta el poder de la tecnología en tu negocio.
          </h1>
          <p className="text-xl font-semibold text-zinc-600">
            Hacemos el trabajo de las personas mas fácil a través de nuestras
            soluciones tecnológicas.
          </p>
          <div className="flex gap-4">
            <button className="rounded-lg border bg-[#BF1922] px-3 py-2 font-semibold text-white">
              Contáctanos
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
